name: Firmware Build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-firmware.yml'
      - 'src/**'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-firmware.yml'
      - 'src/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: shaguarger/platformio
      volumes:
        - ${{ github.workspace }}:/src

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      # Runs a single command using the runners shell
      - name: Build Firmware esp32c3
        run: |
          cd /src
          pio run -e esp32c3

      # Runs a set of commands using the runners shell
      - name: Package Firmware
        uses: 'actions/upload-artifact@v2'
        with:
          name: firmware
          path: |
            /src/.pio/build/*/*.bin
          retention-days: 60
          if-no-files-found: error
